name: ci

on: [push, pull_request]

jobs:
  uv-example:
    name: python
    runs-on: Windows-latest

    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
      - uses: actions/checkout@v4

      - name: run pre-commit
        run: uv run pre-commit run -a

      - name: run unittest
        run: uv run python -m unittest
